export const mandatoryDocsConfig: Record<string, string[]> = {
  CIVIL_CONSTRUCTION: ['TRADE_LICENSE', 'INSURANCE'],
  ELECTRICAL_INSTRUMENTATION: ['TRADE_LICENSE', 'INSURANCE', 'SAFETY_CERTIFICATE'],
  MECHANICAL_FABRICATION: ['TRADE_LICENSE', 'INSURANCE'],
  LOGISTICS_EQUIPMENT: ['INSURANCE'],
  HSE_COMPLIANCE_TESTING: ['SAFETY_CERTIFICATE', 'INSURANCE'],
};
